### ISSUE TITLE
Adding Budgie Themes link to Budgie Welcome Main Menu

### ISSUE THREAD

**Issue by DanielBreuer** [UbuntuBudgie/budgie-welcome#187]
Adding a link to 

Themes

 instead of

Recommendations

 (whits is linked twice) on the "install software" menu
![image](https://user-images.githubusercontent.com/38633335/45252626-1543e600-b35a-11e8-83d5-bcfbe745e827.png)

**Comment by fossfreedom** [comment]
what is linked twice?

Themes & Makeovers isn't really software as such which is why it is the "Default Settings" button.

**Comment by DanielBreuer** [comment]
Well Recommendations is linked twice as you can see on my screenshot (once in the main menu and once in

**Comment by DanielBreuer** [comment]
By the way: the app looks quite nice, but it is not fully intuitive. It is not allways easy to get an continuous and structural arrangement of opiuons and settings - which is also noteable on other OS's like android and windows (they even got their settings double with is really confusing). By i think it is allways a goal to make it easy to use.

**Comment by apolitech** [comment]
in my opinion you need to have 2  apps, 1 for welcome and another for aplets, themes etc, or redesign with one tab special for customization where you find special tabs for each thing from themes to browsers etc

**Comment by DanielBreuer** [comment]
Yeah, like an own "Configuration App" Or "Customisation App". 
It is kind of the thing where we can show that we can do better than windows :P
It could also be linked in settings to get found easier.
Do you know how other distros do handle that customisation stuff?

**Comment by fossfreedom** [comment]
The Recommendations button will most probably be replaced with a "How do I ..." button which will display a page a page of videos that show's a new user how to-do stuff.  So that will resolve "duplicate" issue mentioned.

Disagree for the need of two apps - Applets and Themes have their own menu entries to open those respective welcome pages.

Would welcome any sketches etc on how to improve the intuitiveness of the app.  The caveat here is that suggestions must take notice of the current page structure so not to break translation capabilities that are done on a per page basis.
