### ISSUE TITLE
Popos needs to be removed

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-welcome#202]
The budgie elements of popos gtk theme is not being updated by popos themselves.

We should either remove this as a theme option or swap it for another theme like canta theme or something similar that is both well maintained and most importantly has a ppa that is actively updated.

**Comment by fossfreedom** [comment]
Nice suggestions! Key though are the themes available already packaged plus are they maintained with regular updates?

**Comment by Thomashighbaugh** [comment]
Qogir I know is due to popularity. Other than that, not too sure but capable with CSS, creative and able to maintain one if so desired by the community. Sweet is maintained by Ant's developer (which is a Budgie theme unless I am mistaken and rather new). 

A fork of Plane including its dark mode as a test case I will begin working on to see if my skills are sufficient. I do this with my distros already, I would be using budgie only but for one hang up (please multimonitor panel soon Budgie or somehow support multimonitor window list extension, it makes my life much easier) 

By prepackaged do you mean has a script that runs ```# cp -rnv ~/path/to/theme ~/.themes``` or is there more you would require?

**Comment by fossfreedom** [comment]
Well the team is looking for a keen dedicated maintainer of its main theme Pocillo - https://github.com/UbuntuBudgie/pocillo-gtk-theme

Prepackaged means that there must be a debian package available for it to be installed from i.e.

    sudo add-apt-repository ppa:somemaintainer/their_ppa_name
    sudo apt install theme_package_name

Multimonitor panels is a known issue on the upstream solus-project/budgie-desktop package.  No takers yet on someone with multimonitors who is willing to delve into the code to resolve.
