### ISSUE TITLE
offer option on getting started to disable animation

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-welcome#58]
tentatively adding this issue here - need to see if this really works

We should offer up-front in getting started to offer the option to disable animations - this will make the experience better for low end graphics hardware and those using virtual solutions

    gsettings set org.gnome.settings-daemon.plugins.remote-display active false
    gsettings set org.gnome.desktop.interface enable-animations false

**Comment by niyasc** [comment]
Just tried the animation disable option manually. It makes application menu inactive untill we restart the panel. Restarting panel would require a script. Otherwise we could have changed gsettings in python itself.

Thinking to update our privileged action script to support *Script Execution* action. This will help issues #59, #53 and #43 also.

**Comment by niyasc** [comment]
Addressed this issue by commit https://github.com/UbuntuBudgie/budgie-welcome/commit/f202f1d12f2bb87ed439f830000e07f6e5fd7f14

![enable animation](https://cloud.githubusercontent.com/assets/2451833/20454865/fd7635da-ae71-11e6-8fac-82c967837493.png)
![disable animation](https://cloud.githubusercontent.com/assets/2451833/20454866/feb0d518-ae71-11e6-88ba-971658c8d078.png)
