### ISSUE TITLE
wrong default on the installation help button

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-welcome#86]
![ubuntu budgie zesty builder test running - oracle vm virtualbox_721](https://cloud.githubusercontent.com/assets/996240/22671156/be9ad5e6-ecc4-11e6-88d2-6e4f42a36740.png)

The Install Now option is the default option when you choose "Installation Help".

I'm not sure what "Install Now" is supposed to show - a button to install?

Possibly the default option to be highlighted and show should be the "Installation Preparation" - what do you think?

**Comment by niyasc** [comment]
Well. The blue color is not used to highlight active section. Instead, it is used to catch attention of user as something important

- Actually, the installer is expected to open when we click on it. 
- But it is not working now as, the command associated with that button is now `cmd('install')` instead of `cmd('install-os')` which needs to be fixed.
